### PR TITLE
Jc changing everything

### PR DESCRIPTION
**Pull request by chapmanjamesg**
# Description

I am now printing to both the DOM and the itinerary.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Testing Instructions

git checkout master
git fetch --all
git checkout jc-changing-everything
start http-server
search for a restaurant
hit save on one of the restaurant

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by RyanCrowleyCode — CHANGES_REQUESTED** [review]
meetup code for apiResultsPrinter.js:

// MEETUP
// create an function that builds the HTML string for each meetup.
const buildMeetupHtml = (meetup, number) => {
  return `
<article>
<h4>${meetup.name.text}</h4>
<p>
    <a href="${meetup.url}" target="_blank">${meetup.url}</a>
</p>
<button class="meetup save--${number}" >Save</button>
</article>
`
}

// create a function to display meetups to the DOM
const displayMeetupHtml = meetupArray => {
  let num = 1
  let meetupResultHtml = ""
  if (meetupArray.length <= 4) {
    meetupArray.forEach(meetup => {
        const meetupHtml = buildMeetupHtml(meetup, num)
        meetupResultHtml += meetupHtml
        num += 1 
    } )
  } else {
    for (i = 0; i < 4; i++) {
      const meetupHtml = buildMeetupHtml(meetupArray[i], num)
      meetupResultHtml += meetupHtml
      num += 1
    }
  }

  // then, display this to the DOM
  const searchResultsSection = document.querySelector("#resultsForm")
  searchResultsSection.innerHTML = meetupResultHtml
}

**Review by RyanCrowleyCode — COMMENTED** [review]
Looks good!

**Review by RyanCrowleyCode — APPROVED** [review]
Approve!

**Review by MatthewScott32 — APPROVED** [review]
Noice

**Pull request merged**
