### PR TITLE
Gc parks

### PR DESCRIPTION
**Pull request by cherkesky**
# Testing Instructions

git fetch --all
git checkout MB-Silent-Vampires-7
check function is in parks.js & apiResultsPrinter.js

compare results with https://data.nashville.gov/resource/74d7-b74t.json
test to see it generates itinerary results

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by treysuiter — CHANGES_REQUESTED** [review]
index.html does not need to be changed

**Review by RyanCrowleyCode — CHANGES_REQUESTED** [review]
the order that each javascript file is linked in index.html was changed, please revert back to what we had before. other than that, looks good.

Order should be as below: 

<script src="scripts/apiKeys.js"></script>
    <script src="scripts/meetup.js"></script>
    <script src="scripts/restaurants.js"></script>
    <script src="scripts/concerts.js"></script>
    <script src="scripts/parks.js"></script>
    <script src="scripts/itineraryPrinter.js"></script>
    <script src="scripts/apiResultsPrinter.js"></script>
    <script src="scripts/buildSearchForm.js"></script>
    <script src="scripts/main.js"></script>

**Comment by cherkesky** [comment]
> <script src="scripts/apiKeys.js"></script>
> ```
> <script src="scripts/meetup.js"></script>
> <script src="scripts/restaurants.js"></script>
> <script src="scripts/concerts.js"></script>
> <script src="scripts/parks.js"></script>
> <script src="scripts/itineraryPrinter.js"></script>
> <script src="scripts/apiResultsPrinter.js"></script>
> <script src="scripts/buildSearchForm.js"></script>
> <script src="scripts/main.js"></script>
> ```

fixed it

**Review by RyanCrowleyCode — APPROVED** [review]
Looks great!!

**Comment by cherkesky** [comment]
> index.html does not need to be changed

fixed

**Review by treysuiter — APPROVED** [review]
looks good

**Pull request merged**
