### PR TITLE
spell corrections, work on concert function

### PR DESCRIPTION
**Pull request by MatthewScott32**
# Description

Giant spellcheck and concert functions added

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Testing Instructions

git fetch --all
git checkout MB-Silent-Vampires-3

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by treysuiter — CHANGES_REQUESTED** [review]
resolve conflicts

**Review by RyanCrowleyCode — DISMISSED** [review]
I believe this is good

**Review by treysuiter — DISMISSED** [review]
approve

**Review by RyanCrowleyCode — APPROVED** [review]

**Review by treysuiter — APPROVED** [review]
good

**Pull request merged**
